services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banksdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5433"
  go-bank-backend:
    image: razanakotomandresy/go-bank-backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: banksdb

volumes:
  pgdata:
